---
# tasks file for jenkins(On Linux)
- name: Create directory for Jenkins war file
  file: >
    path="{{ jenkins_war_dir }}"
    state="directory"
    owner="jenkins"
    group="jenkins"
  become: yes
- name: Download specified version of Jenkins war file
  get_url: >
    url="https://updates.jenkins-ci.org/download/war/{{ jenkins_version }}/jenkins.war"
    dest="{{ jenkins_war_dir }}"
    owner="jenkins"
    group="jenkins"
    checksum="sha256:{{ jenkins_sha256 }}"
  become: yes
